"""
[CUSTOM] Generate a per-task environment/files/setup.sh for use with the shared, per-category
images this directory's build_harbor_category_images.py builds (see that script's module
docstring for the full rationale -- this is its companion).

Also installs each task's own `tests/test_requirements.txt` packages.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


SETUP_SH_TEMPLATE = """#!/bin/bash
# [CUSTOM] Generated by write_harbor_task_setup_sh.py -- see that script's module docstring.
set -e

# Deliver task-specific evidence files into the workdir. Replaces the per-task
# `COPY files/ /app/` the shared category image deliberately doesn't bake in.
# $HARBOR_STAGING/env_files is the bind-mounted environment/files/ directory (set by
# bootstrap.sh); exclude this setup.sh itself so it doesn't end up copied into the workdir too.
if [ -d "$HARBOR_STAGING/env_files" ]; then
  find "$HARBOR_STAGING/env_files" -mindepth 1 -maxdepth 1 ! -name setup.sh \\
    -exec cp -r {} "$WORKDIR/" \\;
fi

# Per-task test dependencies (varies per task, can't be pre-baked into the shared category
# image -- see module docstring). --user avoids needing root/--fakeroot for the install
# itself; explicit PYTHONUSERBASE avoids relying on $HOME resolving to anything sane inside
# this container (it doesn't, reliably).
export PYTHONUSERBASE="$WORKDIR/.local"
mkdir -p "$PYTHONUSERBASE"
if [ -f /tests/test_requirements.txt ]; then
  pip3 install --user -r /tests/test_requirements.txt 2>&1 || \\
    echo "[harbor setup.sh] warning: some test_requirements.txt packages failed to install" >&2
fi
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--task-root", type=Path, required=True, help="Root dir holding <category>/<category>_task_NNNN/")
    parser.add_argument("--force", action="store_true", help="Overwrite existing setup.sh files")
    parser.add_argument("--dry-run", action="store_true", help="Print planned writes only")
    return parser.parse_args()


def find_task_dirs(task_root: Path) -> list[Path]:
    return sorted(p.parent.parent for p in task_root.glob("*/*/environment/Dockerfile"))


def main() -> None:
    args = parse_args()
    if not args.task_root.is_dir():
        print(f"Error: task root not found: {args.task_root}", file=sys.stderr)
        sys.exit(2)

    task_dirs = find_task_dirs(args.task_root)
    if not task_dirs:
        print(f"No task directories found under: {args.task_root}")
        return

    print(f"Found {len(task_dirs)} task(s) under: {args.task_root}")
    wrote = skipped = 0
    for task_dir in task_dirs:
        output_path = task_dir / "environment" / "files" / "setup.sh"
        if output_path.exists() and not args.force:
            skipped += 1
            continue
        if args.dry_run:
            print(f"PLAN {output_path}")
            wrote += 1
            continue
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(SETUP_SH_TEMPLATE)
        output_path.chmod(0o755)
        wrote += 1

    print(f"Done. wrote={wrote} skipped={skipped} (existing, use --force to overwrite)")


if __name__ == "__main__":
    main()
